version: '3.4'

services:
  elasticsearch:
    environment:
      - discovery.type=single-node

  diploma.indexingservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - contentStorage:msSqlConnectionString=Server=mssql;Database=ContentStorage;User ID=sa;Password=sa_STRONG_password
      - documentStorage:elasticSearchUri=http://elasticsearch:9200
    ports:
      - "80:80"
