version: '3.4'

services:
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU16-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sa_STRONG_password
    ports:
      - "1433:1433"

  kibana:
    image: kibana:7.4.2
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
