version: '3.4'

services:
  elasticsearch:
    environment:
      - discovery.type=single-node

  diploma.indexingservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - contentStorage:msSqlConnectionString=Server=mssql;Database=ContentStorage
      - documentStorage:elasticSearchUri=http://elasticsearch:9200
    ports:
      - "90:80"
