version: '3.4'

services:
  elasticsearch:
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  mssql:
    ports:
      - "1433:1433"

  diploma.indexingservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - contentStorage:msSqlConnectionString=Server=mssql;Database=ContentStorage;User ID=sa;Password=sa_STRONG_password
      - documentStorage:elasticSearchUri=http://elasticsearch:9200
    ports:
      - "80:80"
    entrypoint: ["/app/wait-for-it.sh", "elasticsearch:9200", "&&", "./wait-for-it.sh", "mssql:1433", "--", "dotnet", "Diploma.IndexingService.Api.dll"]